FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY notification-service/go.mod notification-service/go.sum ./

RUN go mod download

COPY notification-service/ ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /build/notification-service .

FROM alpine:3.22

RUN apk add --no-cache ca-certificates

WORKDIR /app

COPY --from=builder /build/notification-service /app/notification-service

EXPOSE 8084

CMD ["/app/notification-service"]
