FROM golang:1.26.4-alpine AS builder

RUN apk add --no-cache git

WORKDIR /app

COPY . .

# Build user service
WORKDIR /app/user-service
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o /build/user-service .

# Build product service
WORKDIR /app/produk-service
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o /build/product-service .

# Build order service
WORKDIR /app/order-service
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o /build/order-service .

# Build payment service
WORKDIR /app/payment-service
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o /build/payment-service .

FROM alpine:3.22

RUN apk add --no-cache \
    nginx \
    ca-certificates \
    bash

WORKDIR /app

COPY --from=builder /build/user-service /app/user-service
COPY --from=builder /build/product-service /app/product-service
COPY --from=builder /build/order-service /app/order-service
COPY --from=builder /build/payment-service /app/payment-service

COPY nginx.production.conf /etc/nginx/http.d/default.conf
COPY start-backend.sh /app/start-backend.sh

RUN chmod +x /app/start-backend.sh

EXPOSE 8000

CMD ["/app/start-backend.sh"]
