events {
    worker_connections 1024;
}

http {
    server {
        listen 8000;

        # USER SERVICE
        #
        # Contoh:
        # /users/signin
        # ->
        # user-service /signin

        location /users/ {
            proxy_pass http://user_service_container:8084/;

			client_max_body_size 5M;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # PRODUCT SERVICE
        location /products {
            proxy_pass http://product-service:8081;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Authorization $http_authorization;

            client_max_body_size 5M;
        }

        location /uploads/ {
            proxy_pass http://product-service:8081/uploads/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # ORDER SERVICE
        location /orders {
            proxy_pass http://order_service:8082;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # PAYMENT SERVICE
        location /payments {
            proxy_pass http://payment_service:8083;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
