CREATE TABLE IF NOT EXISTS "roles" (
    id SERIAL PRIMARY KEY,
    role_id BIGINT NOT NULL REFERENCES "roles" (id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES "users" (id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT NULL,
    deleted_at TIMESTAMP DEFAULT NULL
);